version: '2'
services:
  neo4j:
    platform: linux/x86_64
    build: ./db
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
  app:
    platform: linux/x86_64
    build: ./app
    environment:
      - RAILS_ENV=development
    command: /myapp/docker-dev-start.sh
    ports:
      - "3000:3000"
    depends_on:
    - neo4j
    volumes:
      - ./app:/myapp
